=== Jihadist/coma/settings/check-board.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="signals" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" type="xs:string" />
                            <xs:element name="start-addr" type="xs:unsignedShort" />
                            <xs:element name="count" type="xs:unsignedShort" />
                        </xs:sequence>
                        <xs:attribute name="type" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="check">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="record" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="group" type="xs:string" />
                                        <xs:element name="record" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence minOccurs="0">
                                                    <xs:element name="start-addr" minOccurs="0" type="xs:unsignedShort" />
                                                    <xs:element name="count" minOccurs="0" type="xs:unsignedShort" />
                                                    <xs:element name="string-array" minOccurs="0" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="desc" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="start-addr" minOccurs="0" type="xs:unsignedShort" />
                                        <xs:element name="count" minOccurs="0" type="xs:unsignedShort" />
                                    </xs:sequence>
                                    <xs:attribute name="header" use="required" />
                                    <xs:attribute name="desc"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="header" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Jihadist/coma/settings/check-3500.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <check header="Текущие данные">
        <signals>
            <type>M_ME</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>101</start-addr>
            <count>2</count>
        </signals>
        <signals>
            <type>M_BO</type>
            <uint-set>
                <item>1</item>
            </uint-set>
            <start-addr>5001</start-addr>
            <count>1</count>
        </signals>
        <record header="Общие">
            <group>1</group>
            <start-addr>101</start-addr>
        </record>
        <record header="Состояния входов">
            <group>1</group>
            <start-addr>5001</start-addr>
        </record>
    </check>
</root>

=== Jihadist/coma/settings/check-8600.xml
<?xml version="1.0" encoding="utf-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="check-board.xsd">
    <signals>
        <type>FLOAT</type>
        <group>200,210</group>
        <start-addr>6040</start-addr>
        <count>36</count>
    </signals>
    <check header="Вибрации">
        <record header="Среднеквадратичные значения виброускорений, м/с2" desc="Датчик №">
            <group>200</group>
            <start-addr>6040</start-addr>
            <count>6</count>
        </record>
        <record header="Среднеквадратичные значения виброскоростей, мм/с" desc="Датчик №">
            <group>200</group>
            <start-addr>6046</start-addr>
            <count>6</count>
        </record>
        <record header="Среднеквадратичные значения виброперемещений, мкм" desc="Датчик №">
            <group>200</group>
            <start-addr>6052</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброускорения, м/с2/час" desc="Датчик №">
            <group>210</group>
            <start-addr>6058</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброскорости, мм/с/час" desc="Датчик №">
            <group>210</group>
            <start-addr>6064</start-addr>
            <count>6</count>
        </record>
        <record header="Скорость изменения среднеквадратичного значения виброперемещения, мкм/час" desc="Датчик №">
            <group>210</group>
            <start-addr>6070</start-addr>
            <count>6</count>
        </record>
    </check>
</root>
